### ISSUE TITLE
Tracking test refactor

### ISSUE THREAD

**Issue by Firedrake969** [Firedrake969/gopher-brain#44]
https://github.com/Firedrake969/gopher-brain/issues/43#issuecomment-239862721

- [x] Immediate node data (e.g. Id, Position, Value)
- [x] OutgoingConnection data - immediate data
- [x] OutgoingConnection data - Node/ConnInfo map data
- [x] IncomingConnection data (only relevant parts) (broken)
